import {db,readWorkspace} from './repository';
import {fail} from './domain';
export async function prepareJob(id:string,fingerprint:string){
 await db()`INSERT INTO journal_ai_jobs(id,fingerprint,status,lease_until) VALUES(${id}::uuid,${fingerprint},'queued',now()+interval '130 seconds') ON CONFLICT(id) DO UPDATE SET status='queued',lease_until=now()+interval '130 seconds',error_code=NULL,error_message=NULL,error_status=NULL,updated_at=now() WHERE journal_ai_jobs.fingerprint=EXCLUDED.fingerprint AND (journal_ai_jobs.status='error' OR journal_ai_jobs.status IN ('queued','running') AND journal_ai_jobs.lease_until<now())`;
 const rows=await db()`SELECT fingerprint,status FROM journal_ai_jobs WHERE id=${id}::uuid`;
 if(rows[0]?.fingerprint!==fingerprint)fail('idempotency','Запрос уже использован с другим содержимым',409);
 return rows[0].status as string;
}
export async function claimJob(id:string,fingerprint:string){const rows=await db()`UPDATE journal_ai_jobs SET status='running',lease_until=now()+interval '130 seconds',updated_at=now() WHERE id=${id}::uuid AND fingerprint=${fingerprint} AND status='queued' RETURNING id`;return rows.length>0;}
export async function finishJob(id:string,response:Response){const result=await response.json();const code=response.ok?null:String(result.code||'unavailable');const message=response.ok?null:String(result.message||'AI временно недоступен. Записи сохранены.');await db()`UPDATE journal_ai_jobs SET status=${response.ok?'done':'error'},error_code=${code},error_message=${message},error_status=${response.ok?null:response.status},updated_at=now(),lease_until=now() WHERE id=${id}::uuid`;}
export async function jobResponse(id:string){const rows=await db()`SELECT status,error_code,error_message,error_status,lease_until<now() AS expired FROM journal_ai_jobs WHERE id=${id}::uuid`;const job=rows[0];if(!job)return Response.json({pending:true},{status:202});if(job.status==='done')return Response.json({state:await readWorkspace()});if(job.status==='error')return Response.json({code:job.error_code,message:job.error_message},{status:job.error_status||503});if(job.expired)return Response.json({code:'ai_timeout',message:'Анализ не завершился вовремя. Записи и черновик сохранены — повтори запрос.'},{status:504});return Response.json({pending:true},{status:202});}
