import {GET,POST} from "../src/server/journal";
import {POST as AI} from "../src/server/ai";
import {readWorkspace,digest} from "../src/lib/repository";
import {Command,Workspace,localDate,commandBasisText} from "../src/lib/domain";
import {Agent,fetch as httpFetch} from "undici";
const smokeAgent=new Agent({connections:2,pipelining:0,connect:{timeout:10000}});
const fetch=(url:string,options:object={})=>httpFetch(url,{...options,dispatcher:smokeAgent});
const apiBase=process.env.SMOKE_API_BASE?.replace(/\/$/,"");
async function snapshot():Promise<Workspace>{if(!apiBase)return readWorkspace();const r=await fetch(apiBase+"/.netlify/functions/journal",{signal:AbortSignal.timeout(60000)});const data=await r.json() as {code?:string;state:Workspace};if(!r.ok)throw new Error(data.code||"read failed");return data.state;}
async function send(route:"journal"|"ai",request:Request){return apiBase?fetch(apiBase+"/.netlify/functions/"+route,{method:request.method,headers:request.headers,body:await request.text(),signal:AbortSignal.timeout(65000)}):route==="journal"?POST(request):AI(request);}
let personId:string|undefined;let initialConsent:boolean|undefined;let step="initial";
async function command(c:Command,requestId=crypto.randomUUID()){const s=await snapshot();const response=await send("journal",new Request("http://127.0.0.1:3101/api/journal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId,revision:s.revision,contentBasis:digest(commandBasisText(s)),command:c})}));const data=await response.json();if(!response.ok)throw new Error(data.code||"CRUD failed");return data.state as Workspace;}
async function ai(payload:object){const requestId=crypto.randomUUID();retry:for(let attempt=0;attempt<5;attempt++){const response=await send("ai",new Request("http://127.0.0.1:3101/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,requestId})}));const data=await response.json();if(attempt<4&&(data.code==="busy"||attempt<1&&data.code==="database")){await new Promise(r=>setTimeout(r,3500));continue;}if(apiBase&&response.status===202){for(let poll=0;poll<140;poll++){await new Promise(r=>setTimeout(r,2000));const checked=await fetch(apiBase+"/.netlify/functions/ai-status?requestId="+requestId,{signal:AbortSignal.timeout(15000)});const result=await checked.json() as Record<string,unknown>;if(checked.status!==202){if(result.code==="busy"&&attempt<4){await new Promise(r=>setTimeout(r,3500));continue retry;}return {...result,status:checked.status};}}throw new Error("background wait timed out");}return {...data,status:response.status};}throw new Error("AI retry exhausted");}
try {
 const initial=await snapshot();initialConsent=initial.consent;const existing=new Set(initial.people.map(x=>x.id));
 const requestId=crypto.randomUUID();const create:Command={kind:"person.save",fields:{name:"Тестовый персонаж · smoke",birth:null,city:"",job:"",context:"Вымышленная тестовая история. Предпочитает заранее согласованные планы.",likes:["прогулки"],dislikes:[]},today:localDate()};
 let s=await command(create,requestId);personId=s.people.find(x=>!existing.has(x.id))!.id;s=await command(create,requestId);if(s.people.filter(x=>x.id===personId).length!==1)throw new Error("duplicate");console.log("Cloud CRUD + idempotency: passed");
 if(!initial.consent)await command({kind:"consent",value:true});
 const texts=["Встретились в кафе. Он предупредил заранее, что придёт на десять минут позже.","Гуляли в парке. Заранее согласовали время и место встречи, пришёл вовремя.","Рассказал, что любит прогулки и предпочитает заранее обсуждать планы.","Отменил встречу за два часа, написал, что заболел. Я расстроился, но причину записал как его слова.","Обсудили перенос встречи. Я сказал, что мне важно предупреждение заранее. Он согласился предложить другое время."];
 for(let i=0;i<4;i++){step="entry "+i;await command({kind:"entry.save",personId,text:texts[i],eventDate:`2026-09-${String(20+i).padStart(2,"0")}`});}
 step="threshold";const blocked=await ai({kind:"signals",personId});if(blocked.status!==403||blocked.code!=="threshold")throw new Error("threshold");console.log("Direct API threshold 4: passed");
 await command({kind:"entry.save",personId,text:texts[4],eventDate:"2026-09-24"});
 if(!process.env.SMOKE_ONLY_B){step="signals";const report=await ai({kind:"signals",personId});if(report.status!==200)throw new Error("signals:"+report.code);if(report.state.reports.find((x:{personId:string})=>x.personId===personId)?.promptVersion!=="2026-10-03.1")throw new Error("old deployed prompt");console.log("Real signals + verified sources + current prompt: passed");
 await new Promise(r=>setTimeout(r,3100));const questions=await ai({kind:"questions",personId,type:"A"});if(questions.status!==200)throw new Error("questions:"+questions.code);const session=questions.state.sessions.filter((x:{personId:string;type:string})=>x.personId===personId&&x.type==="A").at(-1);if(session.questions.length!==3)throw new Error("three questions");console.log("Real A three questions: passed");
 await new Promise(r=>setTimeout(r,3100));const skipped=await ai({kind:"submitA",personId,sessionId:session.id,answers:["-","-","-"]});if(skipped.status!==200)throw new Error("skip:"+skipped.code);console.log("A all skipped atomic packet without model: passed");
 step="A unified signals";await new Promise(r=>setTimeout(r,3100));const nextA=await ai({kind:"questions",personId,type:"A"});if(nextA.status!==200)throw new Error(nextA.code);const newSession=nextA.state.sessions.filter((x:{personId:string;type:string})=>x.personId===personId&&x.type==="A").at(-1);const submitted=await ai({kind:"submitA",personId,sessionId:newSession.id,answers:["Я ценю спокойное обсуждение и хочу заранее согласовывать планы.","Я лично попросил предупреждать о переносе минимум за три часа.","Мне подходят предсказуемые договорённости, это моя личная ценность."]});if(submitted.status!==200)throw new Error(submitted.code+": "+submitted.message);const answerSession=submitted.state.sessions.find((x:{id:string})=>x.id===newSession.id);const unified=submitted.state.reports.find((x:{personId:string})=>x.personId===personId);if(JSON.stringify(unified.result)!==JSON.stringify(answerSession.result)||unified.basis!==answerSession.basis||!unified.result.blocks.some((b:{sources:{id:string}[]})=>b.sources.some(source=>source.id.startsWith(answerSession.packets[0].id+":"))))throw new Error("A signals mismatch");console.log("A answers persisted + single Signals report + verified current answer source: passed");const memories=submitted.state.user.aiContext.filter((m:{personId:string})=>m.personId===personId);if(!memories.length)throw new Error("explicit self-context missing");if(memories.length){const memory=memories[0];let updated=await command({kind:"memory.save",id:memory.id,text:"Исправленный синтетический контекст: ценю спокойный разговор."});if(!updated.user.aiContext?.some(m=>m.id===memory.id&&m.edited&&m.text.startsWith("Исправленный синтетический")))throw new Error("memory edit");updated=await command({kind:"memory.delete",id:memory.id});if(updated.user.aiContext?.some(m=>m.id===memory.id))throw new Error("memory delete");console.log("Automatic user context + edit + delete: passed");}else console.log("Model added no user context on this run; storage/edit tested separately");
 }
 if(!process.env.SMOKE_ONLY_A){step="B questions";await new Promise(r=>setTimeout(r,3100));const b=await ai({kind:"questions",personId,type:"B",userQuestion:"Как спокойно обсудить, что мне важно заранее согласовывать изменения планов?"});if(b.status!==200)throw new Error(b.code);const bs=b.state.sessions.filter((x:{personId:string;type:string})=>x.personId===personId&&x.type==="B").at(-1);if(bs.questions.length!==3)throw new Error("B three");console.log("Real B three questions: passed");
 step="B answer";await new Promise(r=>setTimeout(r,3100));const final=await ai({kind:"submitB",personId,sessionId:bs.id,answers:["Мне важно предупреждение минимум за три часа.","Я хочу обсудить перенос в спокойном разговоре лично.","-"]});if(final.status!==200)throw new Error(final.code+": "+final.message);const done=final.state.sessions.find((x:{id:string})=>x.id===bs.id);if(!done.result.nextStep||!done.result.blocks.some((x:{sources:{id:string}[]})=>x.sources.some(y=>y.id.startsWith(done.packets[0].id+":"))))throw new Error("B ignores answers");console.log("Real B uses submitted answers + next step: passed");
 }
 if(apiBase){step="server tags";const existing=new Set((await snapshot()).entries.map(e=>e.id));const queued=await command({kind:"entry.save",personId:personId!,text:"---",eventDate:localDate()});const marker=queued.entries.find(e=>!existing.has(e.id))!;let tagged=false;for(let poll=0;poll<60;poll++){const current=await snapshot();const e=current.entries.find(e=>e.id===marker.id);if(e?.tagging==="done"&&!e.manualTags){if(e.tags.length)throw new Error("unneeded tags on neutral text");tagged=true;break;}if(e?.tagging==="error")throw new Error("background tag model failed");await new Promise(r=>setTimeout(r,2000));}if(!tagged)throw new Error("background tagging not completed");console.log("Server background tags without browser + empty tags for neutral text: passed");}
 const read=apiBase?await fetch(apiBase+"/.netlify/functions/journal"):await GET();if(!read.ok)throw new Error("read");console.log("Fresh DB read: passed");
}catch(e){console.error("Smoke-test:",step,e instanceof Error?e.message:"failed");process.exitCode=1;}finally{if(personId){try{await command({kind:"person.delete",id:personId});if(initialConsent===false)await command({kind:"consent",value:false});console.log("Only temporary synthetic person removed; consent restored");}catch{console.error("Temporary person cleanup pending");process.exitCode=1;}}}




