import {Agent,fetch} from 'undici';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {Workspace,Command} from '../src/lib/domain';
const base='https://ornate-dolphin-ba40bd.netlify.app/.netlify/functions/journal';
const agent=new Agent({connections:2,pipelining:0});
const name='Тест интерфейса · временный',context='Изолированный вымышленный набор UI-проверки. Можно удалить только этот набор.';
async function read(){const r=await fetch(base,{dispatcher:agent});const b=await r.json() as {state:Workspace;code?:string};if(!r.ok)throw new Error(b.code);return b.state;}
async function command(command:Command){const state=await read();const r=await fetch(base,{method:'POST',dispatcher:agent,headers:{'Content-Type':'application/json',Origin:'https://metal125897.github.io'},body:JSON.stringify({revision:state.revision,requestId:crypto.randomUUID(),command})});const b=await r.json() as {state:Workspace;code?:string};if(!r.ok)throw new Error(b.code);if(r.headers.get('Access-Control-Allow-Origin')!=='https://metal125897.github.io')throw new Error('CORS');return b.state;}
if(process.argv[2]==='prepare'){const before=await read();const old=new Set(before.people.map(p=>p.id));let state=await command({kind:'person.save',fields:{name,birth:null,city:'',job:'',context,likes:[],dislikes:[]},today:'2026-10-01'});const person=state.people.find(p=>!old.has(p.id))!;state=await command({kind:'entry.save',personId:person.id,text:'Вымышленная запись для проверки интерфейса.',eventDate:'2026-10-01'});const entry=state.entries.find(e=>e.personId===person.id)!;await command({kind:'entry.tags',id:entry.id,tags:[]});await mkdir('artifacts',{recursive:true});await writeFile('artifacts/ui-fixture.json',JSON.stringify({personId:person.id,entryId:entry.id}));console.log(JSON.stringify({personId:person.id,entryId:entry.id}));}
else {const fixture=JSON.parse(await readFile('artifacts/ui-fixture.json','utf8')) as {personId:string;entryId:string};const state=await read();const person=state.people.find(p=>p.id===fixture.personId);if(!person||person.name!==name||person.context!==context)throw new Error('Fixture ownership mismatch');if(process.argv[2]==='cleanup'){await command({kind:'person.delete',id:person.id});console.log('Only synthetic UI fixture removed');}else {const e=state.entries.find(e=>e.id===fixture.entryId)!;if(e.text!=='Вымышленная запись после правки через опубликованный интерфейс.'||!e.manualTags||!e.tags.includes('рефлексия'))throw new Error('UI save verification failed');console.log('Browser write + fresh cloud read + CORS: passed');}}
